#!/bin/bash

exitcode=0
while read mount; do
        if ! echo $mount | grep -q "^#" &&  ! echo $mount | grep -q "swap"; then

                mpoint=$(echo $mount | awk '{print $2}')

                grep -q "$mpoint" /etc/mtab
                if [ $? -ne 0 ]; then
                        mount $mpoint 2>/dev/null

                        grep -q "$mpoint" /etc/mtab
                        if [ $? -eq 0 ]; then
                                echo -n "$mpoint mount was not correctly on $(hostname).  This script has mounted it. "
                                if [ $exitcode -ne 2 ]; then
                                         exitcode=1;
                                fi
                        else
                                echo -n "The $mpoint mount is not currently mounted on $(hostname). "
                                exitcode=2;
                        fi
                fi
        fi
done < /etc/fstab

if [ $exitcode -eq 0 ]; then
        echo "Everything is Okay"
fi

exit $exitcode
